return {
    Luck = 0.2, -- If you roll 0.2 or lower, you will not find anything on them. (max is 1.0)
    Tiers = {
        low = { -- All RewardZones with tier = 'low'. It will randomly select 1 reward item and amount.
            {name = 'metalscrap', amount = {min = 1, max = 3}}, 
            {name = 'copper', amount = {min = 1, max = 1}},
        },
        medium = {
            {name = 'rolex', amount = {min = 1, max = 3}},
        },
        high = {
            {name = 'diamond_ring', amount = {min = 1, max = 1}},
        },
    },
    RewardZones = {
        AIRP = { label = 'Los Santos International Airport', tier = 'medium', cash = {min = 45, max = 90}, },
        ALAMO = { label = 'Alamo Sea', tier = 'low', cash = {min = 45, max = 90}, },
        ALTA = { label = 'Alta', tier = 'medium', cash = {min = 45, max = 90}, },
        ARMYB = { label = 'Fort Zancudo', tier = 'low', cash = {min = 45, max = 90}, },
        BANHAMC = { label = 'Banham Canyon Dr', tier = 'low', cash = {min = 45, max = 90}, },
        BANNING = { label = 'Banning', tier = 'low', cash = {min = 45, max = 90}, },
        BEACH = { label = 'Vespucci Beach', tier = 'medium', cash = {min = 45, max = 90}, },
        BHAMCA = { label = 'Banham Canyon', tier = 'low', cash = {min = 45, max = 90}, },
        BRADP = { label = 'Braddock Pass', tier = 'low', cash = {min = 45, max = 90}, },
        BRADT = { label = 'Braddock Tunnel', tier = 'low', cash = {min = 45, max = 90}, },
        BURTON = { label = 'Burton', tier = 'low', cash = {min = 45, max = 90}, },
        CALAFB = { label = 'Calafia Bridge', tier = 'low', cash = {min = 45, max = 90}, },
        CANNY = { label = 'Raton Canyon', tier = 'low', cash = {min = 45, max = 90}, },
        CCREAK = { label = 'Cassidy Creek', tier = 'low', cash = {min = 45, max = 90}, },
        CHAMH = { label = 'Chamberlain Hills', tier = 'high', cash = {min = 45, max = 90}, },
        CHIL = { label = 'Vinewood Hills', tier = 'high', cash = {min = 45, max = 90}, },
        CHU = { label = 'Chumash', tier = 'low', cash = {min = 45, max = 90}, },
        CMSW = { label = 'Chiliad Mountain State Wilderness', tier = 'low', cash = {min = 45, max = 90}, },
        CYPRE = { label = 'Cypress Flats', tier = 'low', cash = {min = 45, max = 90}, },
        DAVIS = { label = 'Davis', tier = 'low', cash = {min = 45, max = 90}, },
        DELBE = { label = 'Del Perro Beach', tier = 'medium', cash = {min = 45, max = 90}, },
        DELPE = { label = 'Del Perro', tier = 'medium', cash = {min = 45, max = 90}, },
        DELSOL = { label = 'La Puerta', tier = 'low', cash = {min = 45, max = 90}, },
        DESRT = { label = 'Grand Senora Desert', tier = 'medium', cash = {min = 45, max = 90}, },
        DOWNT = { label = 'Downtown', tier = 'high', cash = {min = 45, max = 90}, },
        DTVINE = { label = 'Downtown Vinewood', tier = 'high', cash = {min = 45, max = 90}, },
        EAST_V = { label = 'East Vinewood', tier = 'high', cash = {min = 45, max = 90}, },
        EBURO = { label = 'El Burro Heights', tier = 'high', cash = {min = 45, max = 90}, },
        ELGORL = { label = 'El Gordo Lighthouse', tier = 'low', cash = {min = 45, max = 90}, },
        ELYSIAN = { label = 'Elysian Island', tier = 'low', cash = {min = 45, max = 90}, },
        GALFISH = { label = 'Galilee', tier = 'low', cash = {min = 45, max = 90}, },
        GOLF = { label = 'GWC and Golfing Society', tier = 'medium', cash = {min = 45, max = 90}, },
        GRAPES = { label = 'Grapeseed', tier = 'low', cash = {min = 45, max = 90}, },
        GREATC = { label = 'Great Chaparral', tier = 'low', cash = {min = 45, max = 90}, },
        HARMO = { label = 'Harmony', tier = 'medium', cash = {min = 45, max = 90}, },
        HAWICK = { label = 'Hawick', tier = 'high', cash = {min = 45, max = 90}, },
        HORS = { label = 'Vinewood Racetrack', tier = 'high', cash = {min = 45, max = 90}, },
        HUMLAB = { label = 'Humane Labs and Research', tier = 'low', cash = {min = 45, max = 90}, },
        JAIL = { label = 'Bolingbroke Penitentiary', tier = 'low', cash = {min = 45, max = 90}, },
        KOREAT = { label = 'Little Seoul', tier = 'medium', cash = {min = 45, max = 90}, },
        LACT = { label = 'Land Act Reservoir', tier = 'low', cash = {min = 45, max = 90}, },
        LAGO = { label = 'Lago Zancudo', tier = 'low', cash = {min = 45, max = 90}, },
        LDAM = { label = 'Land Act Dam', tier = 'low', cash = {min = 45, max = 90}, },
        LEGSQU = { label = 'Legion Square', tier = 'medium', cash = {min = 45, max = 90}, },
        LMESA = { label = 'La Mesa', tier = 'medium', cash = {min = 45, max = 90}, },
        LOSPUER = { label = 'La Puerta', tier = 'low', cash = {min = 45, max = 90}, },
        MIRR = { label = 'Mirror Park', tier = 'medium', cash = {min = 45, max = 90}, },
        MORN = { label = 'Morningwood', tier = 'medium', cash = {min = 45, max = 90}, },
        MOVIE = { label = 'Richards Majestic', tier = 'high', cash = {min = 45, max = 90}, },
        MTCHIL = { label = 'Mount Chiliad', tier = 'low', cash = {min = 45, max = 90}, },
        MTGORDO = { label = 'Mount Gordo', tier = 'low', cash = {min = 45, max = 90}, },
        MTJOSE = { label = 'Mount Josiah', tier = 'low', cash = {min = 45, max = 90}, },
        MURRI = { label = 'Murrieta Heights', tier = 'low', cash = {min = 45, max = 90}, },
        NCHU = { label = 'North Chumash', tier = 'low', cash = {min = 45, max = 90}, },
        NOOSE = { label = 'N.O.O.S.E', tier = 'low', cash = {min = 45, max = 90}, },
        OCEANA = { label = 'Pacific Ocean', tier = 'low', cash = {min = 45, max = 90}, },
        PALCOV = { label = 'Paleto Cove', tier = 'low', cash = {min = 45, max = 90}, },
        PALETO = { label = 'Paleto Bay', tier = 'low', cash = {min = 45, max = 90}, },
        PALFOR = { label = 'Paleto Forest', tier = 'low', cash = {min = 45, max = 90}, },
        PALHIGH = { label = 'Palomino Highlands', tier = 'low', cash = {min = 45, max = 90}, },
        PALMPOW = { label = 'Palmer-Taylor Power Station', tier = 'low', cash = {min = 45, max = 90}, },
        PBLUFF = { label = 'Pacific Bluffs', tier = 'high', cash = {min = 45, max = 90}, },
        PBOX = { label = 'Pillbox Hill', tier = 'medium', cash = {min = 45, max = 90}, },
        PROCOB = { label = 'Procopio Beach', tier = 'low', cash = {min = 45, max = 90}, },
        RANCHO = { label = 'Rancho', tier = 'low', cash = {min = 45, max = 90}, },
        RGLEN = { label = 'Richman Glen', tier = 'medium', cash = {min = 45, max = 90}, },
        RICHM = { label = 'Richman', tier = 'medium', cash = {min = 45, max = 90}, },
        ROCKF = { label = 'Rockford Hills', tier = 'high', cash = {min = 45, max = 90}, },
        RTRAK = { label = 'Redwood Lights Track', tier = 'low', cash = {min = 45, max = 90}, },
        SANCHIA = { label = 'San Chianski Mountain Range', tier = 'low', cash = {min = 45, max = 90}, },
        SANDY = { label = 'Sandy Shores', tier = 'low', cash = {min = 45, max = 90}, },
        SKID = { label = 'Mission Row', tier = 'medium', cash = {min = 45, max = 90}, },
        SLAB = { label = 'Stab City', tier = 'low', cash = {min = 45, max = 90}, },
        STAD = { label = 'Maze Bank Arena', tier = 'high', cash = {min = 45, max = 90}, },
        STRAW = { label = 'Strawberry', tier = 'low', cash = {min = 45, max = 90}, },
        TATAMO = { label = 'Tataviam Mountains', tier = 'low', cash = {min = 45, max = 90}, },
        TERMINA = { label = 'Terminal', tier = 'low', cash = {min = 45, max = 90}, },
        TEXTI = { label = 'Textile City', tier = 'low', cash = {min = 45, max = 90}, },
        TONGVAH = { label = 'Tongva Hills', tier = 'low', cash = {min = 45, max = 90}, },
        TONGVAV = { label = 'Tongva Valley', tier = 'low', cash = {min = 45, max = 90}, },
        VCANA = { label = 'Vespucci Canals', tier = 'low', cash = {min = 45, max = 90}, },
        VESP = { label = 'Vespucci', tier = 'low', cash = {min = 45, max = 90}, },
        VINE = { label = 'Vinewood', tier = 'low', cash = {min = 45, max = 90}, },
        WINDF = { label = 'Ron Alternates Wind Farm', tier = 'low', cash = {min = 45, max = 90}, },
        WVINE = { label = 'West Vinewood', tier = 'low', cash = {min = 45, max = 90}, },
        ZANCUDO = { label = 'Zancudo River', tier = 'low', cash = {min = 45, max = 90}, },
        ZQ_UAR = { label = 'UFO', tier = 'low', cash = {min = 45, max = 90}, },
    }    
}